### ISSUE TITLE
Only audio records, no video

### ISSUE THREAD

**Issue by davidscholberg** [ProfessorKaos64/jb_live#1]
I'm having an issue recording the streams. When I run any of the scripts, either manually or via cron, the resulting file only plays audio. My system is a fully updated Arch install with the stock ffmpeg package from the Arch repos.

Below is a pastebin of the entire output of a manual run of the jb_live_LAS.sh script. As mentioned above, the resulting file only played audio (tested in mplayer and vlc, both of them being the stock Arch packages). After 5 seconds, I hit "q" to kill ffmpeg, but even if I let it run for longer, the result is the same.

http://slexy.org/view/s2MAHHnNAW

**Comment by davidscholberg** [comment]
Also, here's the full output when I try to play the resulting file in mplayer.

http://slexy.org/view/s2Kmgit4iI

**Comment by mdeguzis** [comment]
I have a fully updated Arch install as well.  I am not at home at the moment, and on Fedora to boot, so give me some time till this afternoon and I'll look into this the best I can.  I play my video files using VLC.  This is a long debated issue with Chris's audio format encoding as well.  Even if you do not wish to keep it, please install VLC and give the same file a try or a new recording.   It may also be a result of the protocol I am using with ffmpeg.  Let me know how that works.

**Comment by mdeguzis** [comment]
I will also investigate to see if there any alterations can be made for a different capture codec.  Blackout24 was pretty good at helping me with that.  I'll see.

**Comment by davidscholberg** [comment]
I tested VLC as well, and got the same result (audio but no video).

Looking at the output of ffmpeg, it seems that it can't detect the correct parameters for the video codec (lines 170-171). I tried all sorts of values for the 'analyzeduration' and 'probesize' options, but still no dice.

**Comment by mdeguzis** [comment]
Hmmm, being a fellow Arch user, it is odd.  I had no issue a few hours ago, but I understand not everyone is the same. Rest assured though, I will try to make this work as best I can.  I am even looking into other capture options for folks in spare time.  If blackout24 or anyone wants to help, that would be welcome as well.

**Comment by mdeguzis** [comment]
I just tested the HLS stream capture with VLC, see below for the sample 30 second command.  See if that works.  I will be adding the VLC capture options to the repo this afternoon.

[code]
vlc http://videocdn-us.geocdn.scaleengine.net/jblive-iphone/live/jblive.stream/playlist.m3u8 --stop-time=30 --sout="#std{access=file,mux=mkv,dst='output2.mkv'}" vlc://quit
[/code]

**Comment by davidscholberg** [comment]
Wow, this one actually worked, although it was hit or miss; sometimes it wouldn't record anything. And it always ended with a "Segmentation fault" error. Still, when it does work, it works very well.

Might I recommend using "cvlc" for the capture command? That way, you don't have to start up the VLC GUI just to record the show.

Thanks for the help!

**Comment by mdeguzis** [comment]
Ah, that's right sorry about cvlc.  And the hit and miss, I will work on that.  Good things take time!  I am no ffmpeg "expert" or vlc expert, but I will keep working at this.  I will create a "Testing VLC" folder under the repo with a testing script for now.  At least give people something to work with in the meantime.

The errors for VLC look like this on my end: http://bpaste.net/show/snZ6dXGHABTTwhrnYGcp/.

And again , it is hit and miss if it happens.  Working towards a stable solution will take time until I can must various options, may it be ffmpeg, vlc, or any other option.

**Comment by mdeguzis** [comment]
You'll also notice I have the folders seperated now for ffmpeg and vlc, and will add any other "methods" I can find.

**Comment by mdeguzis** [comment]
Update: LAS , using the ffmpeg mehod, worked today!  Resulted in a 744 MB file.  Video looks good, watching it now.  So I'm sure we have some things to work though on various others issues, but locally here on Arch, I got a nice live capture :)

**Comment by davidscholberg** [comment]
I'm starting to wonder if my home ISP (Cox) is modifying the stream packets in some way. It really wouldn't surprise me given that they've made similar dick moves in the past (Cox indeed...). I'll test both the vlc and ffmpeg methods on my VPN and report back.

**Comment by mdeguzis** [comment]
Thanks, appreciate it.  ffmpeg works great at home.  I have my entire 2 hour LAS recording.  So on my machine I am good.  At this point I am going to investigate every method I can find for recording either RTSP or HLS streams.

**Comment by mdeguzis** [comment]
David.  There were some recent updates for AAC support and forced TCP (vs. UDP timing out every time).  See if that helps.
